### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by tingerrr** [Thumuss/utpm#11]
I've been wondering if this still is or will be maintained in the future. I've seen the lat commits on main were 3 months ago, and the last active commit on #9 was 2 months ago.

During some work on packages, specifically their docs, I frequently fix packages and checkout the PRs locally to use in my docs' generation until they land in Typst universe, this comes at the cost of using a fork of a package for the docs. Most if not all packages I work on run CI to verify that docs, examples and tests compile and pass, this is not possible without also checking out and installing those forks in CI.

I've considered using utpm for this and have tried it out locally, while it generally did what I expected it to it had some rough edges that prevent me from using it in CI. I'm wondering if you still have time to maintain this, if you need help or can't maintain it actively anymore.

If the latter is the case, consider transferring the repo to @typst-community so it can be maintained by the community in the meanwhile.

**Comment by Thumuss** [comment]
To give you a real answer, yes it will.
I was working on my exams and my year wasn't  good enough to work on my personal project like UTPM. I have a lot of work now but I got motivation to work on it!

But like you said, if I have a lack of motivation or I don't have time like in the past, I'll give them the project.

To continue this topic, you got some rough edges on utpm, I'm sorry to hear that. If you have any recommendations on how to upgrade this project, I'll be pleased to hear from you.

Have an excellent day/night!

**Comment by tingerrr** [comment]
> To continue this topic, you got some rough edges on utpm, I'm sorry to hear that. If you have any recommendations on how to upgrade this project, I'll be pleased to hear from you.

I'll see to trying it out again so I can report any bugs I find.

**Comment by Thumuss** [comment]
Closing for now, if we need to talk about it, I'll open it again.

**Comment by Thumuss** [comment]
Again, my studies are taking all of my free time, I'll try to post an update when my holidays will comes.

**Comment by Thumuss** [comment]
I finally have a schedule that permits me to work on this project, I'll be back soon!
