### ISSUE TITLE
Allow cloning preview packages to local namespace

### ISSUE THREAD

**Issue by mintyfrankie** [Thumuss/utpm#25]
Thanks first for creating this handy CLI tool!

As a developer of a [Typst template package](https://github.com/mintyfrankie/brilliant-CV), `utpm` can be really helpful for me and the users of the template if two functionalities could be considered:

- Allowing "cloning" preview packages to local namespace: some command like `utpm workspace clone @preview/brilliant-cv:2.0.0` creates a `@local/brilliant-cv:2.0.0`, and users can make local modifications to the package without worrying being overwrited or messing with the upstream version;
- A `utpm workspace link --overwrite` like command that overwrites the `preview` namespace package rather than the `local` one: this can be super handy for me, as a developer, to test in a WYSIWYG way my template files.

What do you think?

Thanks a lot!

**Comment by Thumuss** [comment]
First of all, thank you for you issue! 

Cloning is really a good idea, I'll work on it! It will not be a big issue, I'll try to work on this now!

For the overwrite part, it could be a good idea to enhance the property `namespace` in the `[tool.utpm]` section. `--overwrite` will just confirm the overwrite like a `-y` on a package manager.

**Comment by mintyfrankie** [comment]
Great to hear back!

Yeah it would be great to have cloning feature, happy to test it out if you'd like :)

**Comment by Thumuss** [comment]
I've written everything on the PR of #27, you can already try if you want and give me a feedback! I'll merge it in a few days if everything is good for you!

**Comment by mintyfrankie** [comment]
Cool! I will test out the PR today to see if everything is okay, much appreciated for your reactiveness!

**Comment by mintyfrankie** [comment]
Hi @Thumuss, just try to run over the test, and I encountered this error when doing either `cargo build` from `dev-cloning` branch or `cargo install` directly.

```
error[E0432]: unresolved import `crate::build`
  --> src/commands.rs:20:5
   |
20 | use crate::build;
   |     ^^^^^^^^^^^^ no `build` in the root
   |
help: consider importing this module instead
   |
20 | use git2::build;
   |     ~~~~~~~~~~~

For more information about this error, try `rustc --explain E0432`.
error: could not compile `utpm` (bin "utpm-ci") due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

Can you please confirm if it is reproduceable? Thanks!

**Comment by Thumuss** [comment]
> Can you please confirm if it is reproduceable? Thanks!

Yes I can confirm that I have the same error when I'm using `cargo build`, but when using `cargo build --release --bin utpm` I don't have any problem. I'll create an issue and I'll search after!

Try `cargo build --release --bin utpm`  to build it directly of the branch, you will have the binary in `target/release/utpm`!

**Comment by Thumuss** [comment]
Problem solved! Thank you!

**Comment by mintyfrankie** [comment]
Happy to help! I confirmed that I can install the branch via `cargo install`, thanks!

When playing out with the command I've encountered for example this error:

```bash
❯ utpm ws clone @preview/brilliant-cv:2.0.1
2024-08-19T18:27:32.551559Z ERROR utpm::commands::clone: package not found, input: @preview/brilliant-cv:2.0.1
2024-08-19T18:27:32.551594Z ERROR utpm: PackageNotValid Error:
Can't extract your package. Example of a package: @namespace/package:1.0.0
```

Whereas `typst init @preview/brilliant-cv:2.0.1` can download and bootstrap the template without any problem. 

Any clues?

**Comment by Thumuss** [comment]
> Any clues?

I forgot that you can use `-` in names... I have just pushed an update, I hope that you will be able to test today!

Thanks again, another bug fixed!

**Comment by mintyfrankie** [comment]
Thanks a lot @Thumuss! I confirm that it's working correctly now without any specific issue, thanks!

Just wondering a bit on the behaviour when CLI finds that there are existing files in the working directory, it throws a `ContentFound Error` -- is this an intended design?

I asked because I noticed that the `clone` command copies all files directly on the working directory (for which I imagine your introduce a `ContentFound` Error), whereas the `-s` flag will creates a symlinked folder instead. Would that be more pertinent if we unify this behaviour, by creating a subfolder in either of the situations?

Again, thanks a lot for taking care of this tool!

**Comment by Thumuss** [comment]
> Thanks a lot @Thumuss! I confirm that it's working correctly now without any specific issue, thanks!

Perfect! I'm happy to hear that!

> Just wondering a bit on the behaviour when CLI finds that there are existing files in the working directory, it throws a `ContentFound Error` -- is this an intended design?

It is! We don't want to clone something if there is files in the dir. With `--force` you can bypass that.

> I asked because I noticed that the `clone` command copies all files directly on the working directory (for which I imagine your introduce a `ContentFound` Error), whereas the `-s` flag will creates a symlinked folder instead. Would that be more pertinent if we unify this behaviour, by creating a subfolder in either of the situations?

Indeed you're right, I'll put a new arg to specify the path and normalize the behaviour (it's already possible to change the dir by using `UTPM_CURRENT_DIR` environment variable)

> Again, thanks a lot for taking care of this tool!
Thanks to you! Without a community this tool won't have any value!

**Comment by Thumuss** [comment]
Fixed! Now we have a new argument to specify the path and both have the same behaviour!

**Comment by mintyfrankie** [comment]
Just tested out, LGTM! Thanks a lot :)

Feel free to close the issue if it's good.

**Comment by Thumuss** [comment]
And once again, thank you! Any contribution to this project is a pleasure to work on. Have a great day!
